FROM registry.addmore.de/addmore/php:8.1-apache-buster

ENV APACHE_DOCUMENT_ROOT=/var/www/html/public

WORKDIR /var/www/html

COPY ./contao/etc /usr/local/etc
COPY ./contao/ /var/www/html

RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf; \
  sed -ri -e 's!/var/www/!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf

RUN composer2 self-update -q

ADD --chown=www-data:www-data . .

USER www-data

RUN composer2 install

USER root
CMD ["apache2-foreground"]