version: '3'

name: sa_usecase_2_contao

services:
###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-14}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - db-data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###
  # web:
  #   build:
  #     context: ./contao
  #   ports:
  #     - 8080:80
  #   volumes:
  #     - ./contao/files:/var/www/html/files
  #     - ./contao/templates:/var/www/html/templates
  #   env_file:
  #     - './contao/.env'
  #   links:
  #     - dolt:db

  web:
    build:
      context: ./contao
    ports:
      - 8080:80
    volumes:
      #- .:/var/www/html  # use for development, but run composer install
      - ./contao/files:/var/www/html/files
      - ./contao/templates:/var/www/html/templates
      - ./contao/config:/var/www/html/config
      - ./contao/system/config:/var/www/html/system/config
    links:
    - dolt:dolt
    env_file:
    - './contao/.env'
    environment:
    - docker=true
    - APP_ENV=dev

  dolt:
    build:
      context: ./changed_dolt
    ports:
      - "33200:3306"

  adminer:
    image: adminer:4.8.1
    ports:
      - "8081:8080"
    links:
      - dolt:db

volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
